name: Docker Image CI

on:
  schedule:
    - cron: '0 15 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout buildpack docker assets
      run: ./checkout-buildpack.sh
